os: linux
dist: trusty
cache: false
sudo: required
language: bash
services: docker

addons:
  apt:
    packages:
    - sshpass
    
script:
- docker build -t otakushelter/error:1.0.${TRAVIS_BUILD_NUMBER} -f src/OtakuShelter.Error.Web/Dockerfile .
- docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
- docker push otakushelter/error:1.0.$TRAVIS_BUILD_NUMBER
- |
  sudo sshpass -p $ANSIBLE_PASSWORD ssh -o StrictHostKeyChecking=no $ANSIBLE_CONNECTION \
    "cd /root/OtakuShelter.Infrastructure/src && \
    ansible-playbook deploy.yml \
    -e \"\
    otakushelter_hosts=errors \
    otakushelter_nginx_server_name=error.otaku-shelter.ru \
    otakushelter_nginx_proxy_pass=http://localhost:4006 \
    otakushelter_nginx_config=error \
    otakushelter_container=otakushelter_error \
    otakushelter_image=otakushelter/error \
    otakushelter_port=4006 \
    otakushelter_build_number=$TRAVIS_BUILD_NUMBER \
    otakushelter_database_password=$OTAKUSHELTER_DATABASE_PASSWORD \
    otakushelter_secret=$OTAKUSHELTER_SECRET\" \
    -i inventories/staging"