// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;


namespace OtakuShelter.Errors.Migrations
{
    [DbContext(typeof(ErrorsContext))]
    [Migration("20190228174252_AddTraceId")]
    partial class AddTraceId
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("OtakuShelter.Errors.Error", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnName("created");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnName("message");

                    b.Property<string>("Project")
                        .IsRequired()
                        .HasColumnName("project")
                        .HasMaxLength(25);

                    b.Property<string>("StackTrace")
                        .IsRequired()
                        .HasColumnName("stack_trace");

                    b.Property<string>("TraceId")
                        .IsRequired()
                        .HasColumnName("trace_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnName("type")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("TraceId")
                        .IsUnique()
                        .HasName("UI_trace_id");

                    b.ToTable("errors");
                });
#pragma warning restore 612, 618
        }
    }
}
